name: Cypress Tests

on: [push]

jobs:
  cypress-run-chrome-87:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          
  cypress-run-chrome-87-mobile:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config: "viewportWidth=375,viewportHeight=667"
          
  cypress-run-firefox-82:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node14.17.0-chrome88-ff89
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
     
          
  cypress-run-firefox-82-mobile:
     runs-on: ubuntu-latest
     container: 
      image: cypress/browsers:node14.17.0-chrome88-ff89
      options: --user 1001
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          config: "viewportWidth=375,viewportHeight=667"   
